'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Cards',
      [
        {
          question: 'Какую вершину сложно покорить?',
          option1: '0 Фаза',
          option2: '1 Фаза',
          option3: 'Эльбрус',
          option4: 'Эверест',
          right_answer: 'Эльбрус',
          points: 100,
          img_path: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Mount_Elbrus_May_2008.jpg', // Путь к изображению (если нужно)
          deck_id: 3, // Связь с колодой (Deck)
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Местожительства волка – это …',
          option3: 'TypeScript',
          option2: 'Логово',
          option1: 'Лес',
          option4: 'АУФ!',
          right_answer: 'TypeScript',
          points: 100,
          img_path: 'https://static.tildacdn.com/tild3161-3130-4530-b636-666261636335/_03.jpg',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Чем занимаются студенты Эльбруса в выходные?',
          option1: 'Отдыхают',
          option2: 'Кодят',
          option3: 'Отдыхают и Кодят',
          option4: 'Отдыхают и не Кодят',
          right_answer: 'Отдыхают и Кодят',
          points: 100,
          img_path: 'https://news.sfu-kras.ru/files/images/img001_2013-07-22_09-46-08_0.jpg',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Этот человек переживает за ваши Проекты',
          option1: 'Юра',
          option2: 'Макс',
          option3: 'Андрей',
          option4: 'А кто такой Андрей?',
          right_answer: 'Юра',
          points: 100,
          img_path: 'https://img.freepik.com/free-photo/young-builder-man-wearing-construction-uniform-safety-helmet-suffering-from-headache-holding-his-head-with-right-hand-from-headache_141793-33734.jpg',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Именно этих животных ждёт прекрасное будущее',
          option1: 'Буйволы',
          option4: 'Бобры',
          option3: 'От куда здесь появились Совы?',
          option2: 'ВСЕХ ВСЕХ ВСЕХ',
          right_answer: 'ВСЕХ ВСЕХ ВСЕХ',
          points: 100,
          img_path: 'https://cdn.oblakoz.ru/IMUMKContent/688675/content/515027/515286.png',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Что нужно делать утром, чтобы начать этот крутой день?',
          option1: 'Ничего не надо делать',
          option2: 'Хлопнуть в ладоши',
          option3: 'Хлопнуть так, чтобы отвалились руки',
          option4: 'ХЛОПОЧКИ',
          right_answer: 'ХЛОПОЧКИ',
          points: 100,
          img_path: 'https://lovefit.ru/imgs/blog/069/69/blg5e26f7ac5ac385_85536533.jpg',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Из-за чего очень легко опоздать утром на учёбу?',
          option1: 'Лифт',
          option2: 'Опоздание на автобус',
          option3: 'Не сработал будильник',
          option4: 'Поймал рассосик',
          right_answer: 'Лифт',
          points: 100,
          img_path: 'https://www.seeneco.com/wp-content/uploads/2023/10/opozdanie-min-scaled.jpg',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Нельзя оставаться в кампусе на ночь. Почему?',
          option1: 'Ночью по кампусу бродят духи не сдавших экзамен',
          option4: 'Станешь слишком умным',
          option3: 'Ночью слишком хорошо кодится',
          option2: 'Правила таковы и больше не каковы',
          right_answer: 'Правила таковы и больше не каковы',
          points: 100,
          img_path: 'https://img.freepik.com/free-photo/homeless-man-sleeping-cardboard_23-2148464341.jpg',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Из-за чего расстроена девочка на фото в кухне?',
          option4: 'Не работает ESLINT',
          option2: 'Сломался сниппет',
          option3: 'Забуксовала',
          option1: 'Не понимает сложную тему с первого раза',
          right_answer: 'Не понимает сложную тему с первого раза',
          points: 100,
          img_path: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXqyW9uPpdah1ljNeuYaCElXj71Uec9UjpSw&s',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Что нужно сделать, если вылезла ошибка (в консоле или в браузере)?',
          option1: 'Позвать Юру',
          option2: 'Позвать Макса',
          option3: 'Позвать НАПОМОЩЬ!!111',
          option4: 'console.log',
          right_answer: 'console.log',
          points: 100,
          img_path: 'https://remont-pc-moscow.ru/remont/pc_notebook/images/stories/statii50/24775.jpg',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Cards', { deck_id: 3 }, {});
  },
};