'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Cards',
      [
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Portal',
          option2: 'Half-Life 2',
          option3: 'Counter-Strike',
          option4: 'Left 4 Dead',
          right_answer: 'Half-Life 2',
          points: 100,
          img_path: 'https://files.vgtimes.ru/gallery/thumb/16402/6735560370_1681366265_4884.webp',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'The Witcher 3: Wild Hunt',
          option2: 'The Elder Scrolls III: Morrowind',
          option3: 'Dark Souls',
          option4: 'Dragon Age: Origins',
          right_answer: 'The Elder Scrolls III: Morrowind',
          points: 100,
          img_path:
            'https://upload.wikimedia.org/wikipedia/ru/a/aa/The_Elder_Scrolls_III_Morrowind.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'StarCraft II',
          option2: 'Warcraft III: Reign of Chaos',
          option3: 'Age of Empires II',
          option4: 'Diablo III',
          right_answer: 'Warcraft III: Reign of Chaos',
          points: 100,
          img_path: 'https://igrovuha.org/uploads/posts/2019-05/1556739426_2.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Hitman: Blood Money',
          option2: 'Max Payne 2: The Fall of Max Payne',
          option3: 'Splinter Cell: Chaos Theory',
          option4: 'Mafia: The City of Lost Heaven',
          right_answer: 'Max Payne 2: The Fall of Max Payne',
          points: 100,
          img_path:
            'https://i.ytimg.com/vi/dygidc_kBCw/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AHUBoAC4AOKAgwIABABGGMgZShPMA8=&amp;rs=AOn4CLBj5sEXpYuPrwM4jonzOWUY6yFxXg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Devil May Cry',
          option2: 'God of War',
          option3: 'Bayonetta',
          option4: 'Darksiders',
          right_answer: 'God of War',
          points: 100,
          img_path: 'https://i.ytimg.com/vi/Km4930zxUfc/maxresdefault.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'System Shock 2',
          option2: 'BioShock',
          option3: 'Prey',
          option4: 'Dishonored',
          right_answer: 'BioShock',
          points: 100,
          img_path:
            'https://digiseller.mycdn.ink/preview/467960/p1_2301517_0c2399fd.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Saints Row 2',
          option2: 'Grand Theft Auto IV',
          option3: 'Mafia II',
          option4: 'Watch Dogs',
          right_answer: 'Grand Theft Auto IV',
          points: 100,
          img_path:
            'https://i.pinimg.com/originals/d2/b0/25/d2b025b2034e13088f5f9640d8e5d8d7.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Star Wars: Knights of the Old Republic',
          option2: 'Mass Effect',
          option3: 'The Outer Worlds',
          option4: 'Deus Ex: Human Revolution',
          right_answer: 'Mass Effect',
          points: 100,
          img_path: 'https://cdn.mos.cms.futurecdn.net/E8n7CK2eRyVyinjJpTr7u9.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Thief',
          option2: 'Dishonored',
          option3: 'Deus Ex',
          option4: 'Prey',
          right_answer: 'Dishonored',
          points: 100,
          img_path:
            'https://www.newgamenetwork.com/images/uploads/gallery/Dishonored/dishonored_01.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'The Witcher 3: Wild Hunt',
          option2: 'The Elder Scrolls V: Skyrim',
          option3: 'Dragon Age: Inquisition',
          option4: 'Dark Souls',
          right_answer: 'The Elder Scrolls V: Skyrim',
          points: 100,
          img_path:
            'https://cdn.mobygames.com/screenshots/2490934-the-elder-scrolls-v-skyrim-playstation-3-close-combat-with-the-c.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Days Gone',
          option2: 'The Last of Us',
          option3: 'Resident Evil 2 Remake',
          option4: 'Horizon Zero Dawn',
          right_answer: 'The Last of Us',
          points: 100,
          img_path:
            'https://static1.cbrimages.com/wordpress/wp-content/uploads/2022/07/The-Last-Of-Us-Part-1-Ellie-Joel.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'Bloodborne',
          option2: 'Dark Souls II',
          option3: 'Sekiro: Shadows Die Twice',
          option4: 'Nioh',
          right_answer: 'Dark Souls II',
          points: 100,
          img_path:
            'https://www.newgamenetwork.com/images/uploads/gallery/DarkSouls2/ds2_07.jpg',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Какая игра изображена на скриншоте',
          option1: 'The Walking Dead',
          option2: 'Life is Strange',
          option3: 'Until Dawn',
          option4: 'Detroit: Become Human',
          right_answer: 'Life is Strange',
          points: 100,
          img_path:
            'https://etgeekera.com/wp-content/uploads/2016/01/life-is-strange-screenshot-03.jpg?w=848',
          deck_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Cards', null, {});
  },
};