'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Cards',
      [
        {
          question: 'Какую вершину сложно покорить?',
          option1: '0 Фаза',
          option2: '1 Фаза',
          option3: 'Эльбрус',
          option4: 'Эверест',
          right_answer: 'Эльбрус',
          points: 100,
          img_path: '', // Путь к изображению (если нужно)
          deck_id: 3, // Связь с колодой (Deck)
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Местожительства волка – это …',
          option3: 'TypeScript',
          option2: 'Логово',
          option1: 'Лес',
          option4: 'АУФ!',
          right_answer: 'TypeScript',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Чем занимаются студенты Эльбруса в выходные?',
          option1: 'Отдыхают',
          option2: 'Кодят',
          option3: 'Отдыхают и Кодят',
          option4: 'Отдыхают и не Кодят',
          right_answer: 'Отдыхают и Кодят',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Этот человек переживает за ваши Проекты',
          option1: 'Юра',
          option2: 'Макс',
          option3: 'Андрей',
          option4: 'А кто такой Андрей?',
          right_answer: 'Юра',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Именно этих животных ждёт прекрасное будущее',
          option1: 'Буйволы',
          option4: 'Бобры',
          option3: 'От куда здесь появились Совы?',
          option2: 'ВСЕХ ВСЕХ ВСЕХ',
          right_answer: 'ВСЕХ ВСЕХ ВСЕХ',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Что нужно делать утром, чтобы начать этот крутой день?',
          option1: 'Ничего не надо делать',
          option2: 'Хлопнуть в ладоши',
          option3: 'Хлопнуть так, чтобы отвалились руки',
          option4: 'ХЛОПОЧКИ',
          right_answer: 'ХЛОПОЧКИ',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Из-за чего очень легко опоздать утром на учёбу?',
          option1: 'Лифт',
          option2: 'Опоздание на автобус',
          option3: 'Не сработал будильник',
          option4: 'Поймал рассосик',
          right_answer: 'Лифт',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Нельзя оставаться в кампусе на ночь. Почему?',
          option1: 'Ночью по кампусу бродят духи не сдавших экзамен',
          option4: 'Станешь слишком умным',
          option3: 'Ночью слишком хорошо кодится',
          option2: 'Правила таковы и больше не каковы',
          right_answer: 'Правила таковы и больше не каковы',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Из-за чего расстроена девочка на фото в кухне?',
          option4: 'Не работает ESLINT',
          option2: 'Сломался сниппет',
          option3: 'Забуксовала',
          option1: 'Не понимает сложную тему с первого раза',
          right_answer: 'Не понимает сложную тему с первого раза',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question: 'Что нужно сделать, если вылезла ошибка (в консоле или в браузере)?',
          option1: 'Позвать Юру',
          option2: 'Позвать Макса',
          option3: 'Позвать НАПОМОЩЬ!!111',
          option4: 'console.log',
          right_answer: 'console.log',
          points: 100,
          img_path: '',
          deck_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Cards', { deck_id: 3 }, {});
  },
};